server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: back-api

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/hansup
    username: ssafy
    password: hansupssafy1!@#

  jpa:
    hibernate:
      ddl-auto: none 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
        use_sql_comments: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  #mail
  mail:
    host : smtp.gmail.com
    port : 587
    username : porest.help@gmail.com
    password : porest123!@#
    properties.mail.smtp :
      auth : true
      starttls.enable : true

  #redis
  cache :
    type : redis
  redis :
    host : redis
    port : 6379
  data :
    redis :
      repositories :
        enabled : false
jwt:
  secret: ODvkvcbdsSDF23jbxc#@xdfvml2SDFv0b=ckdsikwjcBCxbodjqw^dmSDc
